on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 publishing:
    runs-on: ubuntu-latest
    steps:
      - name: start starter
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{vars.HOST}}
          username: ${{vars.USERNAME}}
          password: ${{vars.PASSWORD}} 
          script: ./dev/start.sh https://github.com/KuzarinM/cicd_test.git main test test
