on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
      - name: Print res
        run: |
          echo  ${{ steps.detect.outputs.changed }}
